### ISSUE TITLE
API service initiated twice

### ISSUE THREAD

**Issue by felixlinker** [TechLabs-Berlin/H8-Identifier#21]
A `service` object to query the YouTube API is initiated twice:
https://github.com/TechLabs-Berlin/H8-Identifier/blob/4bf261581ae90b63f25562db42d0879645ddb2ca/h8_identifier/yt_request.py#L10
https://github.com/TechLabs-Berlin/H8-Identifier/blob/4bf261581ae90b63f25562db42d0879645ddb2ca/h8_identifier/twitter_classifier/url_to_hate.py#L11

I would remove either one of them and have the service object be available globally.

**Comment by thuyanh97** [comment]
Urs, can yt_request be merge to url_to_hate.py? In he latter one I put 1. the url-> id function (for easier test runs) and designed a function to 2. extract only comments text and another to 3. create a dataframe for predict() and the last  4. merges everything to get predictions from vidID. It also doesn't need to be in the classifier folder.

**Comment by ZenVega** [comment]
@thuyanh97  I guess we could. But does that make it easier or better structured? For now I removed the doubled functionality so that yt_request kind of does the request part and url_to hate the transformation. but that still could be clearer. plus the names of Url_to_hate file does not really fit anymore.. how about that we go for three files. request / transformation / classification. and sort the functions accordingly? what do you think?

**Comment by thuyanh97** [comment]
url_to_hate already does request + transformation, maybe missing 1 or 2 functions from yt_request, will  merge the files on my branch and create pull request, so you can test.

**Comment by thuyanh97** [comment]
Good job on updating yt_requests, I did the cleanup as suggested, url_to_hate is now prediction.py (it doesn't belong to classifier folder), Added number of analyzed comment, it is not same as comments count. Thus updated in all the relevant files. I just run flask and it works now. You can even try YoutubeRewind with 2 mio comments without a system crash or API quota issue :)
